services:
  eleventy:
    build:
      context: .
      args:
        COMMIT_HASH: 0000000
    ports:
      - 8080:8080
    command:
      - sh
      - serve.sh
    volumes:
      - ./:/app
    hostname: "eleventy"